# Train–Test Split & Model Evaluation

## Import Libraries

In [2]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split  # A function that splits our dataset into training and testing parts.
from sklearn.tree import DecisionTreeClassifier       # A machine learning model used for classification problems.
from sklearn.metrics import accuracy_score, classification_report # accuracy_score ->Tells how many predictions were correct as a percentage.
                                                                   # classification_report -> Gives precision, recall, F1-score, and support for each class.

## Load a Dataset (Titanic)

In [3]:
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## Select Useful Columns + Clean Data

In [4]:
df = df[['survived','pclass','age','fare','sex']].dropna()

df['sex'] = df['sex'].map({'male': 0, 'female': 1})
df.head()

   survived  pclass   age     fare  sex
0         0       3  22.0   7.2500    0
1         1       1  38.0  71.2833    1
2         1       3  26.0   7.9250    1
3         1       1  35.0  53.1000    1
4         0       3  35.0   8.0500    0

## Split Data into Train–Test

In [5]:
X = df[['pclass','age','fare','sex']]
y = df['survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
df.head

<bound method NDFrame.head of      survived  pclass   age     fare  sex
0           0       3  22.0   7.2500    0
1           1       1  38.0  71.2833    1
2           1       3  26.0   7.9250    1
3           1       1  35.0  53.1000    1
4           0       3  35.0   8.0500    0
..        ...     ...   ...      ...  ...
885         0       3  39.0  29.1250    1
886         0       2  27.0  13.0000    0
887         1       1  19.0  30.0000    1
889         1       1  26.0  30.0000    0
890         0       3  32.0   7.7500    0

[714 rows x 5 columns]>

## Train a Simple Model

In [6]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

## Make Predictions

In [8]:
y_pred = model.predict(X_test)
y_pred

array([1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1])

## Evaluate Our Model

In [9]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.7272727272727273

Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.79      0.78        87
           1       0.66      0.62      0.64        56

    accuracy                           0.73       143
   macro avg       0.71      0.71      0.71       143
weighted avg       0.73      0.73      0.73       143

## Check Overfitting / Underfitting

In [10]:
print("Train Score:", model.score(X_train, y_train))
print("Test Score:", model.score(X_test, y_test))

Train Score: 0.9912434325744308
Test Score: 0.7272727272727273