#### (All of the exercises taken from kaggle.com)

In [2]:
import pandas as pd

# Exercises

### 1.
In the cell below, create a DataFrame fruits that looks like this:

    
![](https://storage.googleapis.com/kaggle-media/learn/images/Ax3pp2A.png)

In [4]:
fruits = pd.DataFrame({'Apples': [30], 'Bananas': [21]})
fruits

   Apples  Bananas
0      30       21

## 2.

Create a dataframe `fruit_sales` that matches the diagram below:

![](https://storage.googleapis.com/kaggle-media/learn/images/CHPn7ZF.png)

In [33]:
fruit_sales = pd.DataFrame({'Apple':[35,41],'Bananas':[21,34]},index=['2017 Sales','2018 Sales'])
fruit_sales

            Apple  Bananas
2017 Sales     35       21
2018 Sales     41       34

## 3.

Create a variable `ingredients` with a Series that looks like:

```
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object
```

In [11]:
ingredients = pd.Series(['4 cups', '1 cup', '2 large', '1 can'],index=['Floue','Milk','Eggs','Spam'],name='Dinner')
ingredients

Floue     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

## 4.

Read the following csv dataset of wine reviews into a DataFrame called `reviews`:

![](https://storage.googleapis.com/kaggle-media/learn/images/74RCZtU.png)

The filepath to the csv file is `../input/wine-reviews/winemag-data_first150k.csv`. The first few lines look like:

```
,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,"This tremendous 100% varietal wine[...]",Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and[...]",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,,Tinta de Toro,Bodega Carmen Rodríguez
```

In [13]:
reviews = pd.read_csv("winemag-data_first150k.csv")
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine offers rich...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,1,Spain,"Ripe aromas of fig, blackberry and chocolate w...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,2,Italy,"Aromas include tropical fruit, honey and white...",Vulkà Bianco,91,15.0,Sicily & Sardinia,Etna,NaN,White Blend,Nicosia
3,3,France,Fresh and vibrant with notes of cherry and spice.,Les Hauts de Smith,94,45.0,Bordeaux,Pessac-Léognan,NaN,Red Bordeaux Blend,Château Smith Haut Lafitte

# Indexing

## 1.

Select the `description` column from `reviews` and assign the result to the variable `desc`.

In [41]:
decs = reviews.description
decs

0    This tremendous 100% varietal wine offers rich...
1    Ripe aromas of fig, blackberry and chocolate w...
2    Aromas include tropical fruit, honey and white...
3    Fresh and vibrant with notes of cherry and spice.
Name: description, dtype: object

## 2.

Select the first value from the description column of `reviews`, assigning it to variable `first_description`.

In [43]:
first_description=reviews.description.iloc[0]
first_description

'This tremendous 100% varietal wine offers rich aromas and a long finish.'

## 3. 

Select the first row of data (the first record) from `reviews`, assigning it to the variable `first_row`.

In [48]:
first_row=reviews.iloc[0,:]
first_row

Unnamed: 0                                                     0
country                                                       US
description    This tremendous 100% varietal wine offers rich...
designation                                    Martha's Vineyard
points                                                        96
price                                                      235.0
province                                              California
region_1                                             Napa Valley
region_2                                                    Napa
variety                                       Cabernet Sauvignon
winery                                                     Heitz
Name: 0, dtype: object

## 4.

Select the first 10 values from the `description` column in `reviews`, assigning the result to variable `first_descriptions`.

Hint: format your output as a pandas Series.

In [50]:
first_description=reviews.description[0:11]
first_description

0    This tremendous 100% varietal wine offers rich...
1    Ripe aromas of fig, blackberry and chocolate w...
2    Aromas include tropical fruit, honey and white...
3    Fresh and vibrant with notes of cherry and spice.
Name: description, dtype: object

# Summary Function

## 1.

What is the median of the `points` column in the `reviews` DataFrame?

In [51]:
median_points = reviews.points.median()
median_points

np.float64(95.0)

## 2. 
What countries are represented in the dataset? (Your answer should not include any duplicates.)

In [54]:
countries = reviews.country.describe()
countries

count      4
unique     4
top       US
freq       1
Name: country, dtype: object

## 3.
How often does each country appear in the dataset? Create a Series `reviews_per_country` mapping countries to the count of reviews of wines from that country.

In [55]:
reviews_per_country = reviews['country'].value_counts()
print(reviews_per_country)

country
US        1
Spain     1
Italy     1
France    1
Name: count, dtype: int64